rvm: 
  - 2.0.0
  - 1.9.3
  - jruby
before_script:
  - "pushd ruby && gem install bundler && bundle && popd"
script: "make travis"
branches:
  only:
    - master
    - /^issue.*$/
    - /^fix.*$/
notifications:
  email:
    - cukes-devs@googlegroups.com
  irc:
    - "irc.freenode.org#cucumber"
